In [1]:
from env_2048 import env_2048
import numpy as np

env = env_2048()
env.reset()
env.render()

[[0. 0. 2. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [4. 0. 0. 0.]]


In [14]:
new_state, reward, done, _ = env.step(1)
print(done)
env.render()

False
[[4. 4. 2. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
